// TIDAL CYCLES

(Quarks.install("SuperDirt");)
(thisProcess.recompile;)
(thisProcess.recompile;)
(SuperDirt.start;)
(~dirt.loadSoundFiles("D:/LIBRERIA/Audio/tidal-cycles-samples-extra/*");)
// if SuperDirt is already running => CMD
// netstat -aon | findstr 57120
// taskkill /PID <PID> /F

// PROXY SPACE

(
    "C:/Users/gabri/Desktop/live-coding/supercollider/setup/Server.scd".load();
)
(
    "C:/Users/gabri/Desktop/live-coding/supercollider/setup/Proxy.scd".load();
)